### PR TITLE
Make unit test working with phpunit 9.x. Based on Debian patch:

### PR DESCRIPTION
**Pull request by Schlue**
https://salsa.debian.org/horde-team/php-horde-activesync/-/blob/debian-sid/debian/patches/1001_phpunit-8.x%2B9.x-without-db-tests.patch

Some test cases do not work:
AutodiscoverTest.php  ImapAdapterTest.php  MessageBodyDataTest.php  ServerTest.php With following error
PHP Fatal error:  Cannot declare class Horde_Controller_Request, because the name is already in use in /usr/share/php/PHPUnit/Framework/MockObject/MockClass.php(51) : eval()'d code on line 3

### CODE REVIEW

**Comment by Schlue** [comment]
@mrubinsk Running the test shows some "PHP Deprecated" outputs.

**Comment by Schlue** [comment]
reopened

**Comment by mrubinsk** [comment]
Appreciate all the work, but unfortunately we cannot merge these changes into the 5_2 branch since we still need to support the advertised minimum version of PHP in that branch.  Changes like this need to be merged into the master branch.

**Comment by Schlue** [comment]
not needed

**Pull request closed without merging**
